export const REQUEST_ORDER_LIST_TO_DJANGO = 'REQUEST_ORDER_LIST_TO_DJANGO'
export const REQUEST_ORDER_TO_DJANGO = 'REQUEST_ORDER_TO_DJANGO'
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER'
export const SET_TOTAL_PAGE_NUMBER = 'SET_TOTAL_PAGE_NUMBER'