# Generated by Django 5.0.6 on 2024-10-07 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=500)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='backlog.backlog')),
            ],
            options={
                'db_table': 'backlog_issue',
            },
        ),
    ]
