# Generated by Django 5.0.6 on 2024-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                ("travelId", models.AutoField(primary_key=True, serialize=False)),
                ("travelName", models.CharField(max_length=128)),
                ("travelLocation", models.CharField(max_length=32)),
                ("travelProperty", models.TextField()),
                ("travelContent", models.TextField()),
                ("travelImage", models.CharField(max_length=100, null=True)),
                ("registeredDate", models.DateTimeField(auto_now_add=True)),
                ("updatedDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "travel",
            },
        ),
    ]
