# Generated by Django 4.2.13 on 2024-09-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'backlog'), (2, 'sprint_term'), (3, 'in_progress'), (4, 'review'), (5, 'completed'), (6, 'additional_work'), (7, 'archived')], default=1)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='backlog.backlog')),
            ],
            options={
                'db_table': 'backlog_status',
            },
        ),
    ]
