# Generated by Django 5.0.6 on 2024-06-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                ("travelId", models.AutoField(primary_key=True, serialize=False)),
                ("travelName", models.CharField(max_length=128)),
                ("travelLocation", models.CharField(max_length=32)),
                ("travelProperty", models.TextField()),
                ("travelContent", models.TextField()),
                ("travelImage", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "travel",
            },
        ),
    ]
