# Generated by Django 4.2.13 on 2024-09-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('survey_type', models.IntegerField(choices=[('1', 'General'), ('2', 'Five Score'), ('3', 'Boolean')], default='1')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
            ],
            options={
                'db_table': 'survey_question',
            },
        ),
    ]
