# Generated by Django 4.2.13 on 2024-09-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Closed')], default=1),
        ),
    ]
