# Generated by Django 4.2.13 on 2024-09-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_survey_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveySelection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("selection_text", models.CharField(max_length=255)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="survey.surveyquestion",
                    ),
                ),
            ],
            options={
                "db_table": "survey_selection",
            },
        ),
    ]
